export enum AUCTIONS_TASKS {
  SCHEDULE_AUCTION = 'SCHEDULE_AUCTION',
  AUCTION_PHASE_START = 'AUCTION_PHASE_START',
  AUCTION_PHASE_BIDDING = 'AUCTION_PHASE_BIDDING',
  AUCTION_PHASE_CLOSED = 'AUCTION_PHASE_CLOSED',
}
